/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package aplikasi;

import java.util.Random;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;


/**
 *
 * @author User
 */
public class undian extends javax.swing.JFrame {


    /**
     * Creates new form undian
     */
    private final String NamaKolom[]={"NIM", "Nama", "Kota Asal"};
    private int JmlBaris=0;
    private int JmlKolom=3;
    private String DataMhs[][]=new String
            [JmlBaris] [JmlKolom];
    private DefaultTableModel model=new
            DefaultTableModel(DataMhs,NamaKolom);
    private int bariske=0;
    
    public undian() {
        initComponents();
    }
    
    public void reset(){
        Fieldnim.setText(null);
        Fieldnama.setText(null);
        Fieldkota.setText(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        Buttundian = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        Belnim = new javax.swing.JLabel();
        Belnama = new javax.swing.JLabel();
        Belkota = new javax.swing.JLabel();
        Fieldnim = new javax.swing.JTextField();
        Fieldnama = new javax.swing.JTextField();
        Fieldkota = new javax.swing.JTextField();
        Buttadd = new javax.swing.JButton();
        Buttdelete = new javax.swing.JButton();
        Buttupdate = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblmhs = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        exit = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.setPreferredSize(new java.awt.Dimension(840, 540));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 204, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel2.setFont(new java.awt.Font("Brighly Crush", 1, 30)); // NOI18N
        jLabel2.setText("APLIKASI UNDIAN MAHASISWA INFORMATIKA");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(12, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, 640, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Downloads\\cloud(2).png")); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 10, 220, 120));

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Downloads\\cloud(2).png")); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 10, 230, 120));

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Downloads\\grades.png")); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 10, 150, 60));

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Downloads\\cloud(2).png")); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, 250, 140));

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Downloads\\cloud(2).png")); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, -10, 220, 160));

        jLabel8.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Downloads\\grades22.png")); // NOI18N
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 50, 130, 100));

        jPanel3.setBackground(new java.awt.Color(204, 204, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        Buttundian.setBackground(new java.awt.Color(255, 204, 102));
        Buttundian.setFont(new java.awt.Font("Courier New", 1, 22)); // NOI18N
        Buttundian.setText("START");
        Buttundian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtundianActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("MS UI Gothic", 1, 18)); // NOI18N
        jLabel10.setText("Klik Start Untuk Memulai Undian");

        jLabel11.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Downloads\\congratulation(2).png")); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(27, 27, 27))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(Buttundian, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel11))
                        .addGap(88, 88, 88))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Buttundian)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 140, 320, 240));

        jPanel4.setBackground(new java.awt.Color(204, 204, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Belnim.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        Belnim.setText("NIM");
        jPanel4.add(Belnim, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 61, -1));

        Belnama.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        Belnama.setText("Nama");
        jPanel4.add(Belnama, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        Belkota.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        Belkota.setText("Kota Asal");
        jPanel4.add(Belkota, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        Fieldnim.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        Fieldnim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FieldnimActionPerformed(evt);
            }
        });
        jPanel4.add(Fieldnim, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, 170, -1));

        Fieldnama.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        jPanel4.add(Fieldnama, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, 170, -1));

        Fieldkota.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        jPanel4.add(Fieldkota, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, 170, -1));

        Buttadd.setBackground(new java.awt.Color(0, 204, 204));
        Buttadd.setFont(new java.awt.Font("Centaur", 1, 12)); // NOI18N
        Buttadd.setText("ADD");
        Buttadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtaddActionPerformed(evt);
            }
        });
        jPanel4.add(Buttadd, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 140, 80, 32));

        Buttdelete.setBackground(new java.awt.Color(0, 204, 204));
        Buttdelete.setFont(new java.awt.Font("Centaur", 1, 12)); // NOI18N
        Buttdelete.setText("DELETE");
        Buttdelete.setPreferredSize(new java.awt.Dimension(51, 23));
        Buttdelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtdeleteActionPerformed(evt);
            }
        });
        jPanel4.add(Buttdelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 80, 80, 32));

        Buttupdate.setBackground(new java.awt.Color(0, 204, 204));
        Buttupdate.setFont(new java.awt.Font("Centaur", 1, 12)); // NOI18N
        Buttupdate.setText("UPDATE");
        Buttupdate.setPreferredSize(new java.awt.Dimension(51, 23));
        Buttupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtupdateActionPerformed(evt);
            }
        });
        jPanel4.add(Buttupdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 30, 80, 32));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, 390, 190));

        jPanel5.setBackground(new java.awt.Color(204, 204, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        tblmhs.setBackground(new java.awt.Color(204, 204, 255));
        tblmhs.setFont(new java.awt.Font("Lucida Sans Typewriter", 0, 11)); // NOI18N
        tblmhs.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NIM", "Nama", "Kota Asal"
            }
        ));
        tblmhs.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                tblmhsAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        tblmhs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblmhsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblmhs);

        jLabel9.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLabel9.setText("Data Mahasiswa Informatika ");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addGap(98, 98, 98))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 350, 390, 160));

        jLabel13.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Downloads\\digital-marketing.png")); // NOI18N
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 290, 150, 120));

        exit.setBackground(new java.awt.Color(255, 102, 102));
        exit.setFont(new java.awt.Font("Rockwell", 1, 20)); // NOI18N
        exit.setText("EXIT");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        jPanel1.add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 480, 90, 40));

        jLabel12.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Downloads\\air-balloon.png")); // NOI18N
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 370, 110, 150));

        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Downloads\\cloud(4).png")); // NOI18N
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 430, 220, 120));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 840, 540));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtundianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtundianActionPerformed
    TableModel dtm = tblmhs.getModel();
    int nRow = dtm.getRowCount(), nCol = dtm.getColumnCount();
    String[]tabeldata = new String[nRow];
    for (int i = 1; i<nRow; i++)
    tabeldata[i] = (String)dtm.getValueAt(i, 1);
        
    Random rnd = new Random();
    int idx = rnd.nextInt(tabeldata.length);
    
    JOptionPane.showMessageDialog(this, "Selamat Untuk Mahasiswa yang Bernama " + tabeldata[idx] );
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtundianActionPerformed

    private void FieldnimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FieldnimActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FieldnimActionPerformed

    private void ButtaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtaddActionPerformed
    DefaultTableModel model = (DefaultTableModel) tblmhs.getModel();
    if (Fieldnim.getText().trim().equals("") || Fieldnama.getText().trim().equals("") || Fieldkota.getText().trim().equals("")) {
        JOptionPane.showMessageDialog(null, "Lengkapi Data Dengan Benar");
    }else{
            model.addRow(new Object[] {Fieldnim.getText(), Fieldnama.getText(), Fieldkota.getText()});
         }
    reset();
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtaddActionPerformed

    private void ButtdeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtdeleteActionPerformed
    Fieldnim.setText("");
    Fieldnama.setText("");
    Fieldkota.setText("");
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtdeleteActionPerformed

    private void tblmhsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblmhsMouseClicked
    DefaultTableModel model = (DefaultTableModel)tblmhs.getModel();
    String nim = model.getValueAt(tblmhs.getSelectedRow(), 0).toString();
    String nama = model.getValueAt(tblmhs.getSelectedRow(), 1).toString();
    String kota = model.getValueAt(tblmhs.getSelectedRow(), 2).toString();
    
    Fieldnim.setText(nim);
    Fieldnama.setText(nama);
    Fieldkota.setText(kota);
        // TODO add your handling code here:
    }//GEN-LAST:event_tblmhsMouseClicked

    private void tblmhsAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_tblmhsAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_tblmhsAncestorAdded

    private void ButtupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtupdateActionPerformed
    DefaultTableModel model = (DefaultTableModel) tblmhs.getModel();
    if (tblmhs.getSelectedRowCount() == 1) {
        
        String nim = Fieldnim.getText();
        String nama = Fieldnama.getText();
        String kota = Fieldkota.getText();
        
        model.setValueAt(nim, tblmhs.getSelectedRow(), 0);
        model.setValueAt(nama, tblmhs.getSelectedRow(), 1);
        model.setValueAt(kota, tblmhs.getSelectedRow(), 2);
        
        JOptionPane.showMessageDialog(this, "Updated");
        
    }else{
        if(tblmhs.getRowCount()==0){
            JOptionPane.showMessageDialog(this, "Empty");
        }else{
            JOptionPane.showMessageDialog(this, "Select Row For Update");
        }
    }  
// TODO add your handling code here:
    }//GEN-LAST:event_ButtupdateActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
    System.exit(0);
        // TODO add your handling code here:
    }//GEN-LAST:event_exitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(undian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(undian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(undian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(undian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new undian().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Belkota;
    private javax.swing.JLabel Belnama;
    private javax.swing.JLabel Belnim;
    private javax.swing.JButton Buttadd;
    private javax.swing.JButton Buttdelete;
    private javax.swing.JButton Buttundian;
    private javax.swing.JButton Buttupdate;
    private javax.swing.JTextField Fieldkota;
    private javax.swing.JTextField Fieldnama;
    private javax.swing.JTextField Fieldnim;
    private javax.swing.JButton exit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblmhs;
    // End of variables declaration//GEN-END:variables
}
